import Container from '@/components/Container';
import Navbar from '@/components/Navbar';
import { marketingConfig } from '@/config/marketing';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import { Inter as FontSans } from 'next/font/google';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-inter',
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={cn('font-sans text-slate-900 antialiased', fontSans.variable)}
    >
      <head />
      <body className="min-h-screen">
        <Container>
          <div className="py-2 m-auto">
            <Navbar items={marketingConfig.mainNav} />
          </div>
        </Container>
        <main>{children}</main>
      </body>
    </html>
  );
}
